# Generated by Django 5.2 on 2025-05-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email_verified",
            new_name="is_email_verified",
        ),
    ]
