# Generated by Django 5.1.3 on 2025-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_email_verified_profile_is_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("agent", "Agent"), ("renter/buyer", "Renter/Buyer")],
                max_length=20,
            ),
        ),
    ]
