# Generated by Django 5.2 on 2025-06-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_passwordresetotp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwordresetotp",
            old_name="code",
            new_name="otp",
        ),
    ]
