# Generated by Django 5.2 on 2025-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
