# Generated by Django 5.1.3 on 2025-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_enquiry_replied_at_enquiry_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="properties/"),
        ),
        migrations.AddField(
            model_name="property",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="properties/"),
        ),
        migrations.AddField(
            model_name="property",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="properties/"),
        ),
        migrations.AddField(
            model_name="property",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="properties/"),
        ),
        migrations.AddField(
            model_name="property",
            name="main_image",
            field=models.ImageField(default="image here", upload_to="properties/"),
        ),
        migrations.DeleteModel(
            name="PropertyImage",
        ),
    ]
