# Generated by Django 5.2 on 2025-06-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_cart_is_paid_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
